### PR TITLE
 Support for both OpenSSL1 & OpenSSL3 using weak attribute approach

### PR DESCRIPTION
**Pull request by Santhosh-K-M**
The changes in this PR are similar to the TileDB changes, where we supported both OpenSSL1 & OpenSSL3 changes.

### CODE REVIEW

**Comment by mlathara** [comment]
Looks like a few files are conflicting - can you resolve the conflicts before we review? @Santhosh-K-M

**Review by nalinigans — APPROVED** [review]
Looks good to me. I am assuming you ran the tests through Valgrind for memory leaks. Please confirm. Thanks.

**Comment by Santhosh-K-M** [comment]
No mem leaks observed in valgrind on both ossl1 & ossl3.

OSSL1, Ubuntu1:

>valgrind --leak-check=yes ./azure-storage-test [blob]
==619982== Memcheck, a memory error detector
==619982== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==619982== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==619982== Command: ./azure-storage-test [blob]
==619982== 
Filters: [blob]
===============================================================================
All tests passed (224 assertions in 4 test cases)

==619982== 
==619982== HEAP SUMMARY:
==619982==     in use at exit: 0 bytes in 0 blocks
==619982==   total heap usage: 56,442 allocs, 56,442 frees, 16,482,786 bytes allocated
==619982== 
==619982== All heap blocks were freed -- no leaks are possible
==619982== 
==619982== For lists of detected and suppressed errors, rerun with: -s
==619982== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

OSSL3, Ubuntu22
>valgrind --leak-check=yes ./azure-storage-test [blob]
==4069027== Memcheck, a memory error detector
==4069027== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==4069027== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==4069027== Command: ./azure-storage-test [blob]
==4069027== 
Filters: [blob]
===============================================================================
All tests passed (224 assertions in 4 test cases)

==4069027== 
==4069027== HEAP SUMMARY:
==4069027==     in use at exit: 0 bytes in 0 blocks
==4069027==   total heap usage: 249,288 allocs, 249,288 frees, 24,817,429 bytes allocated
==4069027== 
==4069027== All heap blocks were freed -- no leaks are possible
==4069027== 
==4069027== For lists of detected and suppressed errors, rerun with: -s
==4069027== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
oda-compute-0-16:~/workbenchKms/2weak-attr-azurite-ONLY/azure-storage-cpplite/build>

**Review by mlathara — APPROVED** [review]
lgtm

**Comment by nalinigans** [comment]
> No mem leaks observed in valgrind on both ossl1 & ossl3.
> 

Nice! Thanks.

**Pull request merged**
